parameters:
    pvr_ezcomment.encryption.class: pvr\EzCommentBundle\Comment\pvrEzCommentEncryption
    pvr_ezcomment.manager.class: pvr\EzCommentBundle\Comment\pvrEzCommentManager
    pvr_ezcomment.maxage: 60
    pvr_ezcomment.twig_extension.class: pvr\EzCommentBundle\Twig\pvrEzCommentExtension

    ezpublish.api.role.limitation_type.content_section.class: eZ\Publish\Core\Limitation\SectionLimitationType


services:
    pvr_ezcomment.manager:
        class: %pvr_ezcomment.manager.class%
        arguments:
            - %pvr_ezcomment.anonymous_access%
            - %pvr_ezcomment.moderating%
            - %pvr_ezcomment.moderate_subject%
            - %pvr_ezcomment.moderate_from%
            - %pvr_ezcomment.moderate_to%
            - %pvr_ezcomment.moderate_template%
            - %pvr_ezcomment.notify_enabled%
            - @service_container

    pvr_ezcomment.encryption:
        class: %pvr_ezcomment.encryption.class%
        arguments:
            - %secret%

    ezpublish.api.role.limitation_type.content_section:
        class: %ezpublish.api.role.limitation_type.content_section.class%
        arguments: [@ezpublish.api.persistence_handler]
        tags:
            - {name: ezpublish.limitationType, alias: ContentSection}

    ezpublish.twig.pvrezcomment_extension:
        class: %pvr_ezcomment.twig_extension.class%
        arguments: [@pvr_ezcomment.manager, @ezpublish.connection]
        tags:
            - { name: twig.extension }